FROM golang:1.9.0

RUN apt-get update && \
    apt-get install -y chromium openjdk-8-jre libxi6 libgconf-2-4 && \
    ln -s /usr/bin/chromium /usr/bin/chromium-browser && \
    echo 'Running godog' && \
    go get github.com/DATA-DOG/godog/cmd/godog && \
    godog -t \"~@wip\" && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY deps/heist/escape-integration-tests/deps/_/escape/escape /usr/bin/escape

